//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleStars.Infrastructure.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ProfileId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
        public int Pin { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
