//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleStars.Infrastructure.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int RegisterId { get; set; }
        public int SessionId { get; set; }
        public int StudentId { get; set; }
        public string Payment { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
