//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleStars.Infrastructure.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Registers = new HashSet<Register>();
        }
    
        public int StudentId { get; set; }
        public int ProfileId { get; set; }
        public string Name { get; set; }
        public string Birthday { get; set; }
        public string Image { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Register> Registers { get; set; }
    }
}
